CREATE TABLE IF NOT EXISTS category
(
    id
        name
);
CREATE TABLE IF NOT EXISTS compilation
( id);
CREATE TABLE IF NOT EXISTS user
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS event
(
    id
        category_id NOT NULL REFERENCES category (id),
);
CREATE TABLE IF NOT EXISTS request
(
    id
        event_id NOT NULL REFERENCES event (id),
    requestor_id NOT NULL REFERENCES user (id),
);
CREATE TABLE IF NOT EXISTS compilation_event
(
    event_id       NOT NULL REFERENCES event (id),
    compilation_id NOT NULL REFERENCES compilation (id),
);