CREATE TABLE IF NOT EXISTS location
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

create table IF NOT EXISTS category
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

-- CREATE TABLE IF NOT EXISTS compilation
-- ( id);

CREATE TABLE IF NOT EXISTS ewm_user
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS event
(
    id                 bigint generated by default as identity,
    annotation         varchar(255),
    confirmed_requests bigint,
    created_on         timestamp,
    description        varchar(255),
    event_date         timestamp,
    state              varchar(255),
    paid               boolean,
    participant_limit  integer,
    published_on       timestamp,
    request_moderation boolean,
    title              varchar(255),
    category_id        bigint not null references category(id),
    initiator_id       bigint not null references ewm_user(id),
    location_id        bigint not null references location(id),
    CONSTRAINT pk_event PRIMARY KEY (id)
);

create table if not exists request
(
    id           bigint generated by default as identity,
    created      timestamp,
    status       varchar(255),
    event_id     bigint not null references event(id),
    requester_id bigint not null references ewm_user(id),
    CONSTRAINT pk_request PRIMARY KEY (id)
);

-- TODO: compilation
-- CREATE TABLE IF NOT EXISTS compilation_event
-- (
--     event_id       NOT NULL REFERENCES event (id),
--     compilation_id NOT NULL REFERENCES compilation (id),
-- );